services:
  worker:
    build: ./worker
    container_name: tecnicos-bot
    restart: unless-stopped
    env_file: .env
    networks:
      - rifabot
    ports:
      - "3100:3100"
    volumes:
      - ./painel:/app/painel:ro
      - ./fotos:/app/fotos
      - ./audios:/app/audios

networks:
  rifabot:
    external: true
    name: telegram-rifa-bot_default
